/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwareapplication;

import java.sql.*;
import javax.swing.JOptionPane;

import java.sql.DriverManager;

/**
 *
 * @author Firefox
 */
public class updataadmin extends javax.swing.JFrame {
private final String url="jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=market user=sa;password=1234;";
    /**
     * Creates new form updataadmin
     */
    public updataadmin() {
        initComponents();
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        }catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this,"Cannot Load JDBC Driver !!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        profidlabel = new javax.swing.JTextField();
        namelabel = new javax.swing.JTextField();
        clearbutton = new javax.swing.JButton();
        updatabutton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        catmangerbutton = new javax.swing.JLabel();
        productmangebutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel7.setBackground(new java.awt.Color(255, 102, 0));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Updata Admin");
        jLabel7.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRODID");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAME");
        jLabel4.setToolTipText("");

        profidlabel.setBackground(new java.awt.Color(255, 255, 255));
        profidlabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        profidlabel.setForeground(new java.awt.Color(255, 102, 51));
        profidlabel.setToolTipText("");
        profidlabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 0)));

        namelabel.setBackground(new java.awt.Color(255, 255, 255));
        namelabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 102, 51));
        namelabel.setToolTipText("");
        namelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 0)));

        clearbutton.setBackground(new java.awt.Color(255, 255, 255));
        clearbutton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 102, 0));
        clearbutton.setText("Clear");
        clearbutton.setToolTipText("");
        clearbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        updatabutton.setBackground(new java.awt.Color(255, 255, 255));
        updatabutton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        updatabutton.setForeground(new java.awt.Color(255, 102, 0));
        updatabutton.setText("Updata");
        updatabutton.setToolTipText("");
        updatabutton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        updatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatabuttonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("X");
        jLabel12.setToolTipText("");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softwareapplication/flowers_12771895 (3).png"))); // NOI18N

        catmangerbutton.setBackground(new java.awt.Color(255, 102, 0));
        catmangerbutton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        catmangerbutton.setForeground(new java.awt.Color(255, 255, 255));
        catmangerbutton.setText("Manger Catogers");
        catmangerbutton.setToolTipText("");
        catmangerbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        catmangerbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                catmangerbuttonMouseDragged(evt);
            }
        });
        catmangerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catmangerbuttonMouseClicked(evt);
            }
        });

        productmangebutton.setBackground(new java.awt.Color(255, 102, 0));
        productmangebutton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        productmangebutton.setForeground(new java.awt.Color(255, 255, 255));
        productmangebutton.setText("Manger Product");
        productmangebutton.setToolTipText("");
        productmangebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        productmangebutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                productmangebuttonMouseDragged(evt);
            }
        });
        productmangebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productmangebuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(195, 195, 195)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(updatabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catmangerbutton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productmangebutton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(profidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(productmangebutton)
                        .addGap(18, 18, 18)
                        .addComponent(catmangerbutton)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catmangerbuttonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catmangerbuttonMouseDragged
       
    }//GEN-LAST:event_catmangerbuttonMouseDragged

    private void productmangebuttonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productmangebuttonMouseDragged
       
    }//GEN-LAST:event_productmangebuttonMouseDragged

    private void productmangebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productmangebuttonMouseClicked
        new mangerproduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productmangebuttonMouseClicked

    private void catmangerbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catmangerbuttonMouseClicked
        new managecategories().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_catmangerbuttonMouseClicked

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
       profidlabel.setText(" ");
        namelabel.setText(" ");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void updatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatabuttonActionPerformed
        String prodid=profidlabel.getText();
      String name=namelabel.getText();
       
        //selectoneloginlabel.setText(catgare);
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;

        if(profidlabel.getText().isEmpty()||namelabel.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information!!!");
        }else{
            try{
                con = DriverManager.getConnection(url);
                stmt = con.createStatement();
                String query = "INSERT INTO market VALUES ('"+prodid+"','"+name+"'"
                + ")";
                int affectsRows = stmt.executeUpdate(query);
                if(affectsRows == 1)
                {
                    JOptionPane.showMessageDialog(this, "Successful Registration !!!");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error !!!");
                }

            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            finally
            {
                if(con !=null ){ try{ con.close(); }catch(Exception ex){}}
                if(stmt !=null ){ try{ stmt.close(); }catch(Exception ex){}}
            }
        }
    }//GEN-LAST:event_updatabuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updataadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catmangerbutton;
    private javax.swing.JButton clearbutton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namelabel;
    private javax.swing.JLabel productmangebutton;
    private javax.swing.JTextField profidlabel;
    private javax.swing.JButton updatabutton;
    // End of variables declaration//GEN-END:variables
}
